version: '3.8'
services:
  api-torrentdownloads:
    build:
      context: ./api-torrentdownloads
      dockerfile: Dockerfile
    ports:
      - ${PORT_API_TORRENTDOWNLOADS_HOSTSIDE}:${PORT}
    environment:
      - NODE_ENV=production
    env_file:
        - .env
    volumes:
        - ${DOWNLOAD_PATH_HOSTSIDE}:${DOWNLOAD_PATH}:rw
  api-torrentsearch:
    build:
      context: ./api-torrentsearch
      dockerfile: Dockerfile
    ports:
      - ${PORT_API_TORRENTSEARCH_HOSTSIDE}:${PORT}
    environment:
      - NODE_ENV=production
    env_file:
        - .env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - ${PORT_FRONTEND_HOSTSIDE}:${PORT}
    depends_on:
      - api-torrentdownloads
    environment:
      - NODE_ENV=production
    env_file:
        - .env
